[Thu Mar 03 18:44:19.544422 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62082] PHP Fatal error:  Uncaught Error: Undefined constant "_DIR_" in C:\\xampp\\htdocs\\konyvtar\\public\\index.php:2\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\public\\index.php on line 2
[Thu Mar 03 18:45:13.162417 2022] [php:warn] [pid 3248:tid 1884] [client 127.0.0.1:62086] PHP Warning:  Undefined variable $action in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 29
[Thu Mar 03 18:45:13.162417 2022] [php:warn] [pid 3248:tid 1884] [client 127.0.0.1:62086] PHP Warning:  Undefined variable $action in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 31
[Thu Mar 03 18:45:13.162417 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62086] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:31\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(31): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 31
[Thu Mar 03 18:47:21.607045 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62089] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:45\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 45
[Thu Mar 03 18:47:23.454440 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62089] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:45\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 45
[Thu Mar 03 18:48:35.292870 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62090] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:48:36.123977 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62090] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:48:36.626547 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62090] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:49:03.435549 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62092] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:50:37.328589 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62102] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/home', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:50:37.344559 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62102] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/favicon.ico', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36, referer: http://localhost:8001/home
[Thu Mar 03 18:50:38.526348 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62103] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:36\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(36): call_user_func(NULL)\n#1 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/home', 'GET')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 36
[Thu Mar 03 18:59:18.225347 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62127] PHP Fatal error:  Uncaught Error: Class "App\\Exception\\RouteNotFoundException" not found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 18:59:18.249905 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62127] PHP Fatal error:  Uncaught Error: Class "App\\Exception\\RouteNotFoundException" not found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(21): App\\Router->resolve('/favicon.ico', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35, referer: http://localhost:8001/cica
[Thu Mar 03 19:00:54.161537 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62129] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 19:00:54.177162 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62129] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/favicon.ico', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35, referer: http://localhost:8001/cica
[Thu Mar 03 19:00:55.342388 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62130] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 19:00:56.598852 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62130] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 19:01:05.772817 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62131] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 19:01:56.513284 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:55211] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 19:02:27.068643 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:55212] PHP Fatal error:  Uncaught App\\Exception\\RouteNotFoundException: 404 File Not Found in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php:35\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/cica', 'GET')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Router.php on line 35
[Thu Mar 03 20:30:20.679259 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62203] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:30:58.521618 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62204] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:32:44.236613 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62207] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:33:56.922328 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62208] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:33:57.792443 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62209] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:34:37.741385 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62210] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function App\\Controller\\LibraryController::loadDataFromJSON(), 0 passed in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 16 and exactly 1 expected in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:18\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(16): App\\Controller\\LibraryController->loadDataFromJSON()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 18
[Thu Mar 03 20:35:04.128652 2022] [php:warn] [pid 3248:tid 1884] [client 127.0.0.1:62215] PHP Warning:  Undefined variable $data in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 22
[Thu Mar 03 21:00:06.569443 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62255] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property App\\Controller\\LibraryController::$books of type array in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:22\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(18): App\\Controller\\LibraryController->loadDataFromJSON('C:\\\\xampp\\\\htdocs...')\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 22
[Thu Mar 03 21:00:09.180636 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:62255] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property App\\Controller\\LibraryController::$books of type array in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:22\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(18): App\\Controller\\LibraryController->loadDataFromJSON('C:\\\\xampp\\\\htdocs...')\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#2 [internal function]: App\\Controller\\LibraryController->index()\n#3 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#4 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 22
[Thu Mar 03 21:05:12.360466 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:56726] PHP Fatal error:  Uncaught ArgumentCountError: json_decode() expects at least 1 argument, 0 given in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:22\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(22): json_decode()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(18): App\\Controller\\LibraryController->loadDataFromJSON('C:\\\\xampp\\\\htdocs...')\n#2 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#3 [internal function]: App\\Controller\\LibraryController->index()\n#4 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#5 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#6 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 22
[Thu Mar 03 21:05:14.366263 2022] [php:error] [pid 3248:tid 1884] [client 127.0.0.1:56727] PHP Fatal error:  Uncaught ArgumentCountError: json_decode() expects at least 1 argument, 0 given in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:22\nStack trace:\n#0 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(22): json_decode()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(18): App\\Controller\\LibraryController->loadDataFromJSON('C:\\\\xampp\\\\htdocs...')\n#2 C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php(11): App\\Controller\\LibraryController->loadData()\n#3 [internal function]: App\\Controller\\LibraryController->index()\n#4 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#5 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(20): App\\Router->resolve('/', 'GET')\n#6 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 22
[Thu Mar 03 21:09:12.802227 2022] [php:warn] [pid 3248:tid 1884] [client 127.0.0.1:56731] PHP Warning:  include(C:\\xampp\\htdocs\\konyvtar\\public\\..\\resources\\view\\create.view.php): Failed to open stream: No such file or directory in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 17, referer: http://localhost:8001/
[Thu Mar 03 21:09:12.802227 2022] [php:warn] [pid 3248:tid 1884] [client 127.0.0.1:56731] PHP Warning:  include(): Failed opening 'C:\\xampp\\htdocs\\konyvtar\\public\\..\\resources\\view\\create.view.php' for inclusion (include_path='C:\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 17, referer: http://localhost:8001/
[Mon Mar 07 20:37:06.355509 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61790] PHP Fatal error:  Uncaught Error: Call to undefined method App\\Router::viewtest() in C:\\xampp\\htdocs\\konyvtar\\public\\index.php:19\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\public\\index.php on line 19
[Mon Mar 07 20:37:06.383475 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61790] PHP Fatal error:  Uncaught Error: Call to undefined method App\\Router::viewtest() in C:\\xampp\\htdocs\\konyvtar\\public\\index.php:19\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\public\\index.php on line 19, referer: http://localhost:8001/
[Mon Mar 07 20:37:31.046546 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61793] PHP Fatal error:  Uncaught Error: Call to undefined method App\\Router::viewtest() in C:\\xampp\\htdocs\\konyvtar\\public\\index.php:19\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\public\\index.php on line 19
[Mon Mar 07 20:39:17.722817 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61794] PHP Parse error:  syntax error, unexpected token "try" in C:\\xampp\\htdocs\\konyvtar\\public\\index.php on line 22
[Mon Mar 07 20:39:41.399356 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61796] PHP Fatal error:  Uncaught Error: Class "App\\View" not found in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:14\nStack trace:\n#0 [internal function]: App\\Controller\\LibraryController->index()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#2 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/', 'GET')\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 14
[Mon Mar 07 20:42:24.897425 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61797] PHP Fatal error:  Uncaught Error: Class "App\\View" not found in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:14\nStack trace:\n#0 [internal function]: App\\Controller\\LibraryController->index()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#2 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/', 'GET')\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 14
[Mon Mar 07 20:42:30.346478 2022] [php:error] [pid 7264:tid 1880] [client 127.0.0.1:61798] PHP Fatal error:  Uncaught Error: Class "App\\View" not found in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php:14\nStack trace:\n#0 [internal function]: App\\Controller\\LibraryController->index()\n#1 C:\\xampp\\htdocs\\konyvtar\\app\\Router.php(45): call_user_func_array(Array, Array)\n#2 C:\\xampp\\htdocs\\konyvtar\\public\\index.php(23): App\\Router->resolve('/', 'GET')\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\konyvtar\\app\\Controller\\LibaryController.php on line 14
